const WHY_STATEMENTS: Record<string, string> = {
  bpc157: 'Accelerates the healing of tendons, ligaments, muscles, and the gut lining by promoting blood vessel growth and collagen production directly at the injury site.',
  tb500: 'Speeds up systemic tissue repair, improves flexibility, and lowers inflammation across the entire body by accelerating cell migration to injured zones.',
  semaglutide: 'Promotes sustained weight loss and healthy blood sugar control by mimicking natural satiety hormones to reduce appetite and silence food cravings.',
  tirzepatide: 'Provides dual-action weight management and metabolic support by targeting both GLP-1 and GIP pathways to significantly lower appetite and optimize fat utilization.',
  ghkcu: 'Promotes youthful, glowing skin and thicker hair by stimulating collagen, protecting the dermal barrier, and repairing environmental cell damage.',
  copperpeptide: 'Promotes youthful, glowing skin and thicker hair by stimulating collagen, protecting the dermal barrier, and repairing environmental cell damage.',
  tesamorelin: 'Specially designed to reduce deep abdominal visceral fat while supporting lean muscle recovery and physical tone by stimulating growth hormone release.',
  epitalon: 'A powerful longevity peptide that regulates pineal gland function and acts on telomeres to promote systemic cellular rejuvenation and healthier sleep cycles.',
  epithalon: 'A powerful longevity peptide that regulates pineal gland function and acts on telomeres to promote systemic cellular rejuvenation and healthier sleep cycles.',
  motsc: 'Boosts cellular energy, physical endurance, and metabolic rate by acting directly on mitochondria to mimic the positive effects of intense exercise.',
  kpv: 'Cools down severe digestive spasms and systemic mast cell/histamine reactions by targeting cellular inflammation and reinforcing gut barrier integrity.',
  ara290: 'Activates natural nerve repair and blood vessel growth pathways to reduce chronic neuropathic pain, nerve-related numbness, and daily fatigue.',
  cagrilintidesemaglutide: 'A highly potent co-agonist blend that silences food cravings and promotes weight loss from two separate angles by combining amylin and GLP-1 satiety pathways.',
  cagrisema: 'A highly potent co-agonist blend that silences food cravings and promotes weight loss from two separate angles by combining amylin and GLP-1 satiety pathways.',
  retatrutide: 'A next-generation triple-hormone agonist that maximizes fat metabolism, aids liver fat clearance, and preserves bone and muscle density during weight management.',
  thymosinalpha1: 'Modulates and strengthens the immune system to help the body defend itself against chronic infections, viral loads, and systemic immune imbalances.',
  ta1: 'Modulates and strengthens the immune system to help the body defend itself against chronic infections, viral loads, and systemic immune imbalances.',
  glow50: 'A targeted skincare peptide blend formulated to stimulate subdermal collagen density and skin bounce while smoothing dynamic expression lines.',
  glow50cosmeticblend: 'A targeted skincare peptide blend formulated to stimulate subdermal collagen density and skin bounce while smoothing dynamic expression lines.',
  foxo4dri: 'Promotes healthy aging by selectively targeting and clearing out dysfunctional, non-dividing senescent cells to allow healthy tissues to thrive.',
  dsip: 'Helps restore normal circadian rhythm and deep, slow-wave sleep cycles by modulating natural sleep-inducing neurochemical pathways.',
  hexarelin: 'Stimulates powerful, pulse-like growth hormone releases to accelerate muscle building, fat loss, and tendon healing, with a notable increase in cardiovascular strength.',
  adipotide: 'An experimental weight loss peptide that targets and restricts the blood supply of white fat cells, prompting rapid reductions in subcutaneous fat deposits.',
  testosterone: 'Replaces deficient androgen signaling in confirmed hypogonadism to support sexual function, lean mass, bone health, and erythropoiesis while requiring hematocrit, blood pressure, fertility, and prostate-risk monitoring.',
  testosteronepropionate: 'Short-ester injectable testosterone for confirmed hypogonadism TRT that needs every-other-day or daily injections for stable levels, supporting sexual function, lean mass, and energy with hematocrit, blood pressure, and fertility monitoring.',
  tadalafil: 'Supports healthy cardiovascular circulation, workout muscle pumps, and male erectile function by promoting nitric oxide-mediated blood vessel relaxation.',
  vardenafil: 'Promotes rapid blood vessel relaxation and healthy circulation to support workout performance, male erectile health, and arterial wellness.',
  thymalin: 'Supports thymus gland health to regulate immune cell response, balance inflammatory markers, and promote cardiovascular and endocrine system recovery.',
  turinabol: 'A classic strength-building compound that increases protein synthesis and nitrogen retention to support dry, lean muscle gains and physical performance.',
  dianabol: 'Promotes rapid muscle mass and strength gains by dramatically increasing protein synthesis and glycogen retention in active muscle tissues.',
  naselankamidate: 'An enhanced, fast-acting calming peptide that soothens the nervous system and lowers anxiety without causing drowsiness or brain fog.',
  hcg: 'Mimics natural LH signals to support endogenous testosterone production, maintain testicular volume, and regulate fertility during hormonal cycles.',
  hmg: 'Directly supplies FSH and LH activity to restore natural hormone production, support testicular wellness, and promote healthy spermatogenesis.',
  ll37: 'An antimicrobial peptide that reinforces the immune system\'s barrier defenses to help clear localized bacterial, viral, and fungal infections.',
  selank: 'Provides gentle anxiety relief, quietens background mental noise, and enhances social ease by balancing GABA and other calming brain chemicals.',
  sermorelin: 'A classic growth hormone secretagogue that encourages natural nocturnal growth hormone release to support sleep quality, muscle tone, and recovery.',
  snap8: 'A cosmetic peptide that relaxes expression-related facial muscles to reduce the depth and formation of dynamic forehead and eye wrinkles.',
  hgh: 'Directly supplies human growth hormone to accelerate cellular regeneration, fat loss, muscle preservation, joint healing, and systemic tissue repair.',
  semax: 'Enhances cognitive focus, memory consolidation, and mental clarity by increasing key brain-derived growth factors (BDNF and NGF).',
  nasemaxamidate: 'A fast-acting, highly stable cognitive enhancer that improves attention, drive, and mental stamina during long periods of intellectual tasks.',
  'nad+': 'Boosts cellular ATP production, repairs damaged DNA, and activates longevity pathways by directly replenishing the body\'s essential NAD+ coenzyme pools.',
  nad: 'Boosts cellular ATP production, repairs damaged DNA, and activates longevity pathways by directly replenishing the body\'s essential NAD+ coenzyme pools.',
  oxytocin: 'Reduces social anxiety and lowers daily stress levels by soothing the brain\'s threat-detection centers to promote trust, warmth, and bonding.',
  ghrp2: 'Triggers a high-amplitude release of growth hormone to speed up physical recovery, while gently stimulating appetite to support mass and recovery.',
  ghrp6: 'Stimulates growth hormone release and triggers appetite pathways, making it popular for off-season athletes looking to eat and rebuild muscles.',
  ipamorelin: 'Triggers selective, wave-like growth hormone pulses to support deep sleep, fat loss, and muscle preservation without affecting cortisol or prolactin.',
  cagrilintide: 'Induces persistent satiety and slows down digestion by acting as a long-acting amylin receptor agonist to help manage caloric intake.',
  glow70: 'A premium triple-blend cosmetic formula that relaxes expression micro-muscles while delivering vital copper cofactors to rebuild skin collagen.',
  glow70cosmeticblend: 'A premium triple-blend cosmetic formula that relaxes expression micro-muscles while delivering vital copper cofactors to rebuild skin collagen.',
  cjc1295nodac: 'Primes the pituitary gland to release natural, wave-like growth hormone pulses, supporting cellular repair, deep sleep, and metabolism.',
  cjc1295nodacipamorelin: 'A powerful synergistic GHRH/GHRP combination that primes and triggers growth hormone release for maximum physical recovery, fat loss, and deep sleep.',
  cjc1295nodacipamorelinmix: 'A powerful synergistic GHRH/GHRP combination that primes and triggers growth hormone release for maximum physical recovery, fat loss, and deep sleep.',
  bpc157tb500: 'Combines localized blood vessel growth and systemic cell mobility pathways to deliver unmatched acceleration in tendon, ligament, and muscle healing.',
  bpc157tb500mix: 'Combines localized blood vessel growth and systemic cell mobility pathways to deliver unmatched acceleration in tendon, ligament, and muscle healing.',
  aod9604: 'A growth-hormone fragment researched for fat loss that aims to trigger fat breakdown and limit fat storage without the growth or blood-sugar effects of full HGH, though its clinical weight-loss benefit remains unproven.',
  igf1lr3: 'A long-acting IGF-1 analogue researched for muscle growth and tissue repair by strongly activating growth and glucose-uptake pathways; a high-risk research chemical with serious hypoglycemia and uncontrolled-growth concerns.',
  melanotan1: 'A melanocortin peptide that darkens skin and adds sun-independent photoprotection by stimulating melanin; the implant form (afamelanotide) is FDA-approved for a rare light sensitivity, while injectable tanning use is unapproved and warrants mole monitoring.',
  pe2228: 'A spadin-derived peptide investigated as a fast-acting antidepressant by blocking the TREK-1 potassium channel to lift neuronal activity and neurogenesis, with evidence that is preclinical only and no human data.',
  ss31: 'A mitochondria-targeting peptide (elamipretide) studied for cellular energy and longevity by stabilizing cardiolipin to improve mitochondrial efficiency; FDA-approved only for Barth syndrome and investigational for other uses.',
  'tb500fragment(889da)': 'The small actin-binding fragment of Thymosin Beta-4 used for soft-tissue recovery by promoting cell migration and blood-vessel growth, with evidence largely preclinical and extrapolated from the full-length peptide.',
};

export function getCompoundWhyStatement(name: string): string | null {
  const norm = name.toLowerCase().trim().replace(/[-\s\/]/g, '');
  return WHY_STATEMENTS[norm] ?? null;
}
